import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { validateDocument } from "./schema-validator.js";
import { selectorCandidates } from "./planner.js";

function slugify(value) {
  return String(value).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48) || "flow";
}

function expectationToPlaywright(expectation) {
  const escaped = String(expectation).replace(/[/\\^$*+?.()|[\]{}]/g, "\\$&").slice(0, 80);
  if (/no error|absent|no record/i.test(expectation)) return null;
  return `await expect(page.getByText(/${escaped}/i).first()).toBeVisible();`;
}

export function planToSpecs({ plan } = {}) {
  const specs = [];
  for (const flow of plan?.flows ?? []) {
    const id = slugify(flow.id.replace(/^flow_/, ""));
    specs.push({
      version: 1,
      id,
      title: flow.title,
      environment: "local",
      steps: (flow.steps ?? []).map((step) => ({
        intent: step.intent,
        expect: step.expect,
      })),
      _flowId: flow.id,
      _targetRefs: (flow.steps ?? []).map((step) => step.targetRef ?? null),
    });
  }
  return specs;
}

export function bindLocators({ spec, flow, siteMap } = {}) {
  const pageForms = new Map((siteMap?.pages ?? []).map((page) => [page.path, page.forms ?? []]));
  const bindings = [];
  (spec.steps ?? []).forEach((step, index) => {
    const flowStep = flow?.steps?.[index] ?? {};
    const pagePath = flowStep.page ?? flow?.pages?.[0] ?? "/";
    const targetRef = spec._targetRefs?.[index] ?? flowStep.targetRef ?? null;
    let candidates = [{ strategy: "text", value: step.intent.slice(0, 48), confidence: 0.6 }];
    if (targetRef && targetRef.startsWith("form:")) {
      const formIndex = Number(targetRef.slice(5)) || 0;
      const form = (pageForms.get(pagePath) ?? [])[formIndex];
      if (form) {
        const firstInput = (form.inputs ?? [])[0];
        candidates = selectorCandidates({
          testid: undefined,
          role: "button",
          name: (form.buttons ?? [])[0] ?? step.intent.slice(0, 32),
          text: (form.buttons ?? [])[0] ?? firstInput?.name ?? step.intent.slice(0, 32),
          tag: "button",
        });
      }
    }
    bindings.push({ stepIndex: index + 1, targetRef, page: pagePath, candidates, resolvedStrategy: candidates[0].strategy, assertionValidated: true });
  });
  return { specId: spec.id, origin: siteMap?.origin ?? "", validated: true, validatedAt: new Date().toISOString(), probeSource: "planner", bindings };
}

export async function validateSelectors({ sidecar, origin, fetchImpl = globalThis.fetch, executor, emit } = {}) {
  let validated = true;
  const bindings = [];
  for (const binding of sidecar?.bindings ?? []) {
    let resolvedStrategy = binding.candidates?.[0]?.strategy ?? "text";
    let probeSource = "planner";
    let assertionValidated = true;
    try {
      if (executor?.observe) {
        await executor.observe(binding.candidates?.[0]?.value ?? "", {});
        probeSource = "executor";
      } else if (origin && fetchImpl) {
        const response = await fetchImpl(new URL(binding.page ?? "/", origin).href);
        const html = typeof response.text === "function" ? await response.text() : "";
        const hit = (binding.candidates ?? []).some((candidate) => {
          const needle = typeof candidate.value === "string" ? candidate.value.slice(0, 24) : candidate.value?.[1]?.name ?? "";
          return needle && html.toLowerCase().includes(String(needle).toLowerCase().slice(0, 12));
        });
        if (!hit) {
          const fallback = (binding.candidates ?? []).find((c) => c.strategy === "text" || c.strategy === "css");
          resolvedStrategy = fallback?.strategy ?? resolvedStrategy;
          probeSource = "fetch";
        } else {
          probeSource = "fetch";
        }
      }
    } catch {
      validated = false;
      assertionValidated = false;
    }
    bindings.push({ ...binding, resolvedStrategy, probeSource, assertionValidated });
    if (!assertionValidated) validated = false;
    await emit?.("generate", "selector_validated", { message: `${sidecar.specId} step ${binding.stepIndex}: ${resolvedStrategy}` });
  }
  return { validated, bindings, probeSource: bindings[0]?.probeSource ?? "planner" };
}

export function renderPlaywrightSpec({ spec, flow, sidecar, validation, origin } = {}) {
  const validated = validation?.validated ?? sidecar?.validated ?? false;
  const header = [
    "// AUTOGENERATED by qa-agent orchestrate — do not edit.",
    `// source of truth: .qa/specs/${spec.id}.yaml   locators: ${spec.id}.locators.json`,
    `// flow: ${flow?.id ?? spec._flowId ?? spec.id} (${flow?.category ?? "happy"})  rationale: ${flow?.rationale ?? "planner synthesis"}`,
    `// validated: ${validated}  probe: ${validation?.probeSource ?? sidecar?.probeSource ?? "planner"}`,
    "import { test, expect } from '@playwright/test';",
    "import { resolve } from './_resolve.js';",
    `import chain from './${spec.id}.locators.json' with { type: 'json' };`,
    "",
    `const BASE = process.env.QA_BASE_URL ?? '${origin ?? "http://127.0.0.1:3000"}';`,
    "",
    `${validated ? "" : "test.fixme('unvalidated selectors — see locators.json', async () => {});\n"}`,
    `test('${String(spec.title).replace(/'/g, "\\'")}', async ({ page }) => {`,
  ];
  const body = [];
  (spec.steps ?? []).forEach((step, index) => {
    const binding = (validation?.bindings ?? sidecar?.bindings ?? [])[index];
    const pagePath = binding?.page ?? flow?.pages?.[0] ?? "/";
    body.push(`  // intent: ${step.intent}`);
    if (index === 0 || binding?.page !== (validation?.bindings ?? sidecar?.bindings ?? [])[index - 1]?.page) {
      body.push(`  await page.goto(\`\${BASE}${pagePath}\`);`);
    }
    body.push(`  await (await resolve(page, chain.bindings[${index}].candidates)).click();`);
    for (const expectation of step.expect ?? []) {
      const assertion = expectationToPlaywright(expectation);
      if (assertion) body.push(`  ${assertion} // expect: ${expectation}`);
    }
    body.push("");
  });
  return `${[...header, ...body, "});", ""].join("\n")}`;
}

export function renderResolveHelper() {
  return `const build = (page, c) => ({
  testid: () => page.getByTestId(c.value),
  role: () => page.getByRole(...c.value),
  label: () => page.getByLabel(c.value),
  text: () => page.getByText(c.value, { exact: false }),
  css: () => page.locator(c.value),
}[c.strategy]());

export async function resolve(page, candidates, { timeout = 2000 } = {}) {
  const attempts = [];
  for (const c of candidates) {
    const loc = build(page, c).first();
    try {
      await loc.waitFor({ state: 'attached', timeout });
      attempts.push({ ...c, ok: true });
      if (attempts.length > 1) console.log('[heal] locator fallback ->', JSON.stringify(attempts));
      return loc;
    } catch {
      attempts.push({ ...c, ok: false });
    }
  }
  const err = new Error(\`locator chain exhausted: \${JSON.stringify(attempts)}\`);
  err.chainAttempts = attempts;
  throw err;
}
`;
}

export async function generate({ workspace, plan, siteMap, origin, fetchImpl, executor, outDir, emit } = {}) {
  const specs = planToSpecs({ plan });
  const artifacts = [];
  const generatedDir = outDir ?? `${workspace.qaDirectory}/../generated`;
  await mkdir(generatedDir, { recursive: true });
  await writeFile(path.join(generatedDir, "_resolve.js"), renderResolveHelper());
  let validatedCount = 0;
  const strategies = {};
  const flowMap = {};
  for (const spec of specs) {
    const flow = (plan.flows ?? []).find((f) => f.id === spec._flowId) ?? {};
    const sidecar = bindLocators({ spec, flow, siteMap });
    const validation = await validateSelectors({ sidecar, origin: origin ?? siteMap?.origin, fetchImpl, executor, emit });
    if (validation.validated) validatedCount += 1;
    for (const binding of validation.bindings) {
      strategies[binding.resolvedStrategy] = (strategies[binding.resolvedStrategy] ?? 0) + 1;
    }
    const clean = { ...spec };
    delete clean._flowId;
    delete clean._targetRefs;
    validateDocument("spec", clean);
    await workspace.saveSpec(clean);
    const finalSidecar = { ...sidecar, validated: validation.validated, validatedAt: new Date().toISOString(), probeSource: validation.probeSource, bindings: validation.bindings };
    await writeFile(path.join(generatedDir, `${spec.id}.locators.json`), `${JSON.stringify(finalSidecar, null, 2)}\n`);
    await writeFile(path.join(generatedDir, `${spec.id}.spec.js`), renderPlaywrightSpec({ spec: clean, flow, sidecar: finalSidecar, validation, origin: origin ?? siteMap?.origin }));
    artifacts.push(spec.id);
    if (spec._flowId) flowMap[spec.id] = spec._flowId;
  }
  return { specs: specs.length, validated: validatedCount, unvalidated: specs.length - validatedCount, strategies, dir: generatedDir, artifacts, flowMap };
}
